#!/bin/sh
# HERE BE DRAGONS: you probably don't want to edit this file.
# Local configuration directives go in config.local.
# You can copy lines from here into there, but don't expect things to
# work if you modify them here.
set -a

OBSRVBL_MANAGE_MODE="auto"
OBSRVBL_CONFIG_AUTO="/opt/obsrvbl-ona/config.auto"
OBSRVBL_CONFIG_LOCAL="/opt/obsrvbl-ona/config.local"

# URI for Observable Networks endpoint
OBSRVBL_HOST="https://sensor.ext.obsrvbl.com"

# Service key (if needed)
# OBSRVBL_SERVICE_KEY=""
# Set the HTTPS_PROXY variable if you're using a proxy server
# HTTPS_PROXY=""

##
# pna-monitor
##
OBSRVBL_PNA_SERVICE="true"

# Interfaces the pna software should monitor
OBSRVBL_PNA_IFACES=`ls -1 /sys/class/net/ | grep -v "^lo" || ifconfig -l ether`

# Location of file defining networks and network ids to assign
OBSRVBL_NETWORKS="10.0.0.0/8 172.16.0.0/12 192.168.0.0/16"

# Location to buffer pna files before transfer
PNA_LOGDIR="/opt/obsrvbl-ona/logs/pna"

##
# log-watcher
##
OBSRVBL_LOG_WATCHER="true"

##
# hostname-resolver
##
OBSRVBL_HOSTNAME_RESOLVER="true"
OBSRVBL_HOSTNAME_DNS="true"
OBSRVBL_HOSTNAME_NETBIOS="false"

##
# notification-publisher
##
OBSRVBL_NOTIFICATION_PUBLISHER="true"
OBSRVBL_NOTIFICATION_TYPES="alerts-detail"

##
# pdns-capturer
##
OBSRVBL_PDNS_CAPTURER="true"
OBSRVBL_PDNS_PCAP_DIR="/opt/obsrvbl-ona/logs/pdns"
OBSRVBL_PDNS_CAPTURE_IFACE="any"
OBSRVBL_PDNS_CAPTURE_SECONDS="600"
OBSRVBL_PDNS_PPS_LIMIT="100"

##
# ona-suricata-alert-watcher
##
OBSRVBL_SERVICE_SURICATA="false"

##
# YAF, IPFIX, Netflow
##
OBSRVBL_YAF_CAPTURER="false"
OBSRVBL_IPFIX_CAPTURER="false"
OBSRVBL_IPFIX_LOGDIR="/opt/obsrvbl-ona/logs/ipfix"
OBSRVBL_IPFIX_CONF="/opt/obsrvbl-ona/ipfix/sensor.conf"

# NetFlow v5 exporter
# OBSRVBL_IPFIX_PROBE_0_TYPE="netflow-v5"
# OBSRVBL_IPFIX_PROBE_0_PORT="2055"

# Standard NetFlow v9 exporter
# OBSRVBL_IPFIX_PROBE_1_TYPE="netflow-v9"
# OBSRVBL_IPFIX_PROBE_1_PORT="9995"

# IPFIX exporter
# OBSRVBL_IPFIX_PROBE_2_TYPE="ipfix"
# OBSRVBL_IPFIX_PROBE_2_PORT="9996"

# Cisco ASA exporter
# OBSRVBL_IPFIX_PROBE_3_TYPE="netflow-v9"
# OBSRVBL_IPFIX_PROBE_3_PORT="9997"
# OBSRVBL_IPFIX_PROBE_3_SOURCE="asa"

# Meraki exporter
# OBSRVBL_IPFIX_PROBE_4_TYPE="netflow-v9"
# OBSRVBL_IPFIX_PROBE_4_PORT="9998"
# OBSRVBL_IPFIX_PROBE_4_SOURCE="meraki"

# SonicWALL exporter
# OBSRVBL_IPFIX_PROBE_5_TYPE="netflow-v9"
# OBSRVBL_IPFIX_PROBE_5_PORT="9999"
# OBSRVBL_IPFIX_PROBE_5_SOURCE="sonicwall"

# sFlow exporter
# OBSRVBL_IPFIX_PROBE_6_TYPE="sflow"
# OBSRVBL_IPFIX_PROBE_6_PORT="6343"

##
# ona-syslog-ad-watcher
##
OBSRVBL_SYSLOG_AD_WATCHER="false"

##
# eta-capturer
##
OBSRVBL_ETA_CAPTURER="false"
OBSRVBL_ETA_PCAP_DIR="/opt/obsrvbl-ona/logs/eta"
OBSRVBL_ETA_CAPTURE_IFACE="any"
OBSRVBL_ETA_CAPTURE_SECONDS="600"
OBSRVBL_ETA_CAPTURE_MBITS="32"
OBSRVBL_ETA_UDP_PORT="2055"

##
# kubernetes-watcher
##
OBSRVBL_KUBERNETES_WATCHER="false"


###
# ise-poller
###
OBSRVBL_ISE_POLLER="false"
# OBSRVBL_ISE_SERVER_NAME="localhost"
# OBSRVBL_ISE_NODE_NAME=""
# OBSRVBL_ISE_PASSWORD=""
# OBSRVBL_ISE_CLIENT_CERT="/etc/ise_client_cert.pem"
# OBSRVBL_ISE_CLIENT_KEY="/etc/ise_client_key.pem"
# OBSRVBL_ISE_CA_CERT="/etc/ise_client_key.pem"

# load up auto and local config
[ -f $OBSRVBL_CONFIG_AUTO ] && . $OBSRVBL_CONFIG_AUTO
[ -f $OBSRVBL_CONFIG_LOCAL ] && . $OBSRVBL_CONFIG_LOCAL

set +a
